
spring:

  profiles:
    active: chaos-monkey

  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/chaos_demo_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
