
INSERT INTO CHIMP (NAME, MODIFIED) VALUES ('LITTLE CHIMP', CURRENT_TIMESTAMP);
INSERT INTO CHIMP (NAME, MODIFIED) VALUES ('BROTHER CHIMP', CURRENT_TIMESTAMP);
INSERT INTO CHIMP (NAME, MODIFIED) VALUES ('MOTHER CHIMP' , CURRENT_TIMESTAMP);
INSERT INTO CHIMP (NAME, MODIFIED) VALUES ('FATHER CHIMP', CURRENT_TIMESTAMP);

INSERT INTO GORILLA (NAME, MODIFIED) VALUES ('LITTLE GORILLA', CURRENT_TIMESTAMP);
INSERT INTO GORILLA (NAME, MODIFIED) VALUES ('BROTHER GORILLA', CURRENT_TIMESTAMP);
INSERT INTO GORILLA (NAME, MODIFIED) VALUES ('MOTHER GORILLA', CURRENT_TIMESTAMP);
INSERT INTO GORILLA (NAME, MODIFIED) VALUES ('FATHER GORILLA', CURRENT_TIMESTAMP);

INSERT INTO MONKEY (NAME, MODIFIED) VALUES ('LITTLE MONKEY', CURRENT_TIMESTAMP);
INSERT INTO MONKEY (NAME, MODIFIED) VALUES ('BROTHER MONKEY', CURRENT_TIMESTAMP);
INSERT INTO MONKEY (NAME, MODIFIED) VALUES ('MOTHER MONKEY', CURRENT_TIMESTAMP);
INSERT INTO MONKEY (NAME, MODIFIED) VALUES ('FATHER MONKEY', CURRENT_TIMESTAMP);